Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_download_options = {"ssl-no-revoke" => true}
  config.vm.provider "virtualbox" do |v|
    v.name = "my_vm"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "file", source: "./requirements.txt", destination: "~/project/"

  config.vm.provision "shell", inline: <<-SHELL
    cd ~/project/
    sudo su
    apt update && apt -y upgrade
    apt install -y python3-venv python3-dev build-essential libpq-dev postgresql postgresql-contrib
    mkdir /var/www && cd /var/www
    python3 -m venv env && . ./env/bin/activate
    pip install -U pip
    pip3 install django==3.2.23
    pip3 install psycopg2-binary==2.9.8
  SHELL
end