---
# Install Docker Ubuntu

-
  name: Uninstall old versions packages Ubuntu
  package: name="{{ old_docker_packages }}" state=absent

-
  name: Update packages Ubuntu
  apt:
    update_cache: yes

-
  name: Install required packages Ubuntu
  package: name="{{ required_ubuntu_packages }}" state=present

-
  name: Create keyring directory Ubuntu
  file:
    path: /etc/apt/keyrings
    state: directory

-
  name: Check that the GPG key file Ubuntu
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: stat_result

-
  name: Add Docker's official GPG key to keyring Ubuntu
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  when:
    - not stat_result.stat.exists

-
  name: Check docker repo Ubuntu
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: stat_result_repo

-
  name: Set up Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  when:
    - not stat_result.stat.exists

-
  name: Updates packages Ubuntu
  apt:
    update_cache: yes

-
  name: Install Docker Ubuntu
  package: name="{{ new_docker_packages }}" state=present

-
  name: Ensure group "docker" exists
  group:
    name: docker
    state: present

-
  name: Ensure our user is in group "docker"
  user:
    name: '{{ user }}'
    append: yes
    groups:
      - docker

-
  name: Start and enable Docker service Ubuntu
  systemd:
    name: docker
    enabled: yes
    state: restarted
