apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.1-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx"
              name: config
              readOnly: true
            - name: secret-volume
              mountPath: "/etc/nginx/.htpasswd"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: secret-volume
          secret:
            secretName: auth-basic
---
apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30005