Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos6"
  config.vm.box_download_options = {"ssl-no-revoke" => true}
  config.vm.provider "virtualbox" do |v|
    v.name = "my_vm"
    v.memory = 1024
    v.cpus = 1
  end
#   postgresql-8.4 will be installed by default
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y postgresql postgresql-server postgresql-contrib
    sudo /etc/init.d/postgresql initdb
    sudo /etc/init.d/postgresql start
  SHELL
end